### ISSUE TITLE
Error 404s new Laravel Setup + WP CLI Valet

### ISSUE THREAD

**Issue by jasperf** [aaemnnosttv/wp-cli-valet-command#15]
I have the new setup with Laravel - uninstalled all following instructions at https://laravel.com/docs/5.3/valet - with now NGINX running instead of Caddy. Nice upgrade by Valet.

```
brew services list
Name    Status  User   Plist
dnsmasq started root   /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mariadb started jasper /Users/jasper/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
nginx   started root   /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php70   started root   /Library/LaunchDaemons/homebrew.mxcl.php70.plist
```
wp valet works:

```
wp valet new video-tuts --project=bedrock
Don't go anywhere, this should only take a second...
Success: video-tuts ready! https://video-tuts.localhost
```

But I cannot load the site getting Valet 404s

```
Request URL:https://video-tuts.localhost/
Request Method:GET
Status Code:404 
Remote Address:127.0.0.1:443

```
Valet logs only show things from the day before:

```
Jaspers-Mini:Log jasper$ pwd
/Users/jasper/.valet/Log
Jaspers-Mini:Log jasper$ tail access.log 
91.196.50.33 - [10/Dec/2016:17:05:13 +0300] "GET /server.php HTTP/1.1" 404 233
177.85.188.251 - [10/Dec/2016:17:24:38 +0300] "HEAD /server.php HTTP/1.0" 404 0
::1 - [11/Dec/2016:05:28:57 +0300] "POST /server.php HTTP/2.0" 200 23
```
nginx-error.log is empty:

```
Jaspers-Mini:Log jasper$ tail nginx-error.log
Jaspers-Mini:Log jasper$ 
```

Any ideas?

**Comment by aaemnnosttv** [comment]
This looks like an issue with Laravel Valet v2, not the wp command. There are a few known issues around 404s with WP using the new version.

I would take a look at the issues over on the valet repo and see if any of those sound like what you're seeing.

**Comment by jasperf** [comment]
Yeah, OK. Well , setting domain once more, restarting and starting from scratch seems to have done the trick. All good now. Thanks!

**Comment by cdils** [comment]
I know this issue is closed, but thought I'd drop a comment in case someone is struggling with this. After running `wp valet new mysite`, be sure to cd into the `mysite` directory and run `valet link`. That fixed the 404 issue for me.

https://laravel.com/docs/5.6/valet#serving-sites

**Comment by jasperf** [comment]
@cdils Great tip. Should be added to readme @aaemnnosttv

**Comment by aaemnnosttv** [comment]
This is similar to #22. Valet supports ["parked" directories](https://laravel.com/docs/5.8/valet#the-park-command), that is - a parent directory in which all children directories are considered sites in the same way as a "linked" site, automatically. This is a powerful feature which eliminates the need to do this automatically. There is some value in adding it as an option which is what that issue is requesting and it will likely be added in the future, I just haven't had a chance to do it. In the meantime, I'm happy to consider PRs for updates to the readme or properly implementing #22 as a feature.
