### ISSUE TITLE
Add Debug Settings

### ISSUE THREAD

**Issue by jomurgel** [aaemnnosttv/wp-cli-valet-command#19]
It would be fantastic to be able to enable/disable debug.  --debug=true (perhaps default is false) would output something like:

```define( 'WP_DEBUG', true );```

Right now no debug is present in wp-config.php that is generated with this plugin.

**Comment by aaemnnosttv** [comment]
Not a bad idea, but `--debug` is a reserved global flag in WP-CLI. Not a big obstacle to the feature but just something to think about.

**Comment by emzo** [comment]
Suggestions for an alternative flag name...

- `--wp-debug`
- `--with-debug`
- `--enable-debug`

**Comment by aaemnnosttv** [comment]
So far 2 votes for this. Anyone else? :)

**Comment by javorszky** [comment]
Could this re-use `core config` et al? My config yml has this bit in it: 

```
core config: 
	extra-php: |
		define( 'WP_DEBUG', true );
		define( 'WP_DEBUG_LOG', true );
		define( 'WP_DEBUG_DISPLAY', false );
		define( 'SCRIPT_DEBUG', true );
		@ini_set( 'display_errors', 0 );
		define( 'WCS_DEBUG', true );
```

**Comment by aaemnnosttv** [comment]
This should be possible (see: https://github.com/aaemnnosttv/wp-cli-valet-command/issues/28#issuecomment-353940787)

Does this work for you @javorszky ?

**Comment by aaemnnosttv** [comment]
Closing this for now as rather old but also because there isn't a Bedrock equivalent of this which the command should also support.

The wp-cli config solution proposed by @javorszky should work for normal WP installs although you may need to update it to use the `config create` command now rather than the legacy `core config` command. Thanks all!
