### ISSUE TITLE
Add --bare option?

### ISSUE THREAD

**Issue by tnorthcutt** [aaemnnosttv/wp-cli-valet-command#3]
Would you be open to a PR adding a `--bare` (or other name) option that, following `wp core install`, removes the Hello Dolly and Akismet plugins, as well as the Twenty Fourteen and Twenty Fifteen themes?

I've tested and it works, just wanted to get input before submitting the PR. Cheers!

**Comment by danielbachhuber** [comment]
Isn't there a `no_content` or similar option, where you don't have the `/wp-content` directory included?

https://github.com/wp-cli/wp-cli/issues/1978

**Comment by aaemnnosttv** [comment]
No option like that already Daniel.  It looks like that will come to wp-cli soon as an option for `core download`?

We still need to add support for the option as part of the valet command either way, so I'm definitely open for the PR.

`--bare` sounds good to me.  👍

**Comment by danielbachhuber** [comment]
> No option like that already Daniel. It looks like that will come to wp-cli soon as an option for core download?

As soon as someone submits a PR for it :)

> We still need to add support for the option as part of the valet command either way, so I'm definitely open for the PR.

It would be nice if it used the WP-CLI implementation under the hood though, so you don't reinvent the wheel.

**Comment by tnorthcutt** [comment]
My use-case is to include the wp-content directory and one theme (2016), but no other themes and no plugins. But, I can see how that may not be the most common use-case, so I'm open to suggestions. I'd prefer that `wp-content`, `plugins`, and `themes` at least be created, though.

@aaemnnosttv @danielbachhuber thoughts?

**Comment by aaemnnosttv** [comment]
> It would be nice if it used the WP-CLI implementation under the hood though, so you don't reinvent the wheel.

Oh, agreed.  Yeah, I would rather not have 2 different implementations for core download if this isn't possible yet using options with WP-CLI.

@tnorthcutt perhaps your PR would be best suited on wp-cli/wp-cli#1978 first since there seem to be no takers yet?

This opens another can of worms though, which is the minimum required version of WP-CLI for a package or command (in this case even a flag).  If I want to include the feature, then we need to include our own implementation or under the hood, we also have to 

If the core feature is released let's say with v0.24, we need to ensure it fails gracefully for someone running this command with 0.23.

It might be a nice feature if WP-CLI added support for a required core version annotation?  That way WP-CLI could error before running the command if some part of the synopsis didn't meet the required version.  Just a thought.

**Comment by danielbachhuber** [comment]
> It might be a nice feature if WP-CLI added support for a required core version annotation? That way WP-CLI could error before running the command if some part of the synopsis didn't meet the required version. Just a thought.

Huh, that's an interesting idea.

One way you can do it right now is to perform the version check within command execution:

```
if ( ! version_compare( WP_CLI_VERSION, '0.24.0' ) {
   WP_CLI::warning( "Cleanup not happening" );
}
```

**Comment by aaemnnosttv** [comment]
Going to pass on this one as well for now as it probably isn't worth it to reimplement `core download` for one option now that WP-CLI core will not have this in the foreseeable future either.
