### ISSUE TITLE
Add support for creating new multisite networks

### ISSUE THREAD

**Issue by tnorthcutt** [aaemnnosttv/wp-cli-valet-command#5]
Definitely a feature request/enhancement. Not sure what all is required for this; I haven't used multisite all that much but it would be handy to have 😄

**Comment by aaemnnosttv** [comment]
Looks possible: http://wp-cli.org/commands/core/multisite-install/

My guess is there probably isn't a lot of demand for this feature, so I'll leave this one for a PR unless I'm mistaken :)

**Comment by djdesign** [comment]
@aaemnnosttv will there be support for the multisite feature?

**Comment by aaemnnosttv** [comment]
I'm not planning on adding it myself right now.  I would be open to consider a PR though as long as it didn't require major changes.

**Comment by aaemnnosttv** [comment]
This is currently available in `develop` right now and works nicely. One thing I want it to have before it is released is better support for subdirectory multisites. Since Valet does not work with these by default, we'll need to install a `LocalValetDriver` in the site's root to make it fully compatible. Once this is fleshed out, I'll include this in the next release with some other improvements :)
