### ISSUE TITLE
Get rid of wp_ db name prefix?

### ISSUE THREAD

**Issue by fotan** [aaemnnosttv/wp-cli-valet-command#85]
Is there some way to get rid of the wp_ database name prefix?  Not a huge deal, but it's just annoying enough.

I see the line in config.yml (# dbname: defaults to wp_name) but simply removing wp_ from it give you a db named "name".  Is there some way to insert the site name instead?

**Comment by aaemnnosttv** [comment]
The prefix is only applied to the default `dbname`, so you can currently provide whatever you want by passing the `--dbname=<name>` option which would not be prefixed. I wouldn't recommend using the config for this though because then it would try to create every site using the same DB name unless provided in the command.

It sounds like what you are looking for would be a way to configure the prefix used in the default DB name?

**Comment by fotan** [comment]
Yes.  I was hoping I could just add the site name to the option in the config.  It wouldn't be horrible to just add --dbname=<name> to the command though, if that's the actual string I need to use.

**Comment by aaemnnosttv** [comment]
> It wouldn't be horrible to just add --dbname= to the command though, if that's the actual string I need to use.

Yes. For example, if you wanted a site `my-site` with a matching DB name, you would use this command: 

```
wp valet new my-site --dbname=my-site
```

Obviously the downside is that you're duplicating the name in the command, but this is the way you'd achieve what you are trying to do as things are now.

**Comment by fotan** [comment]
Ok.  That can work.  Much appreciated.
