### ISSUE TITLE
Compatibiliy with Valet+ 3.x

### ISSUE THREAD

**Issue by ianrobertdouglas** [aaemnnosttv/wp-cli-valet-command#92]
Sorry, but I don't know where else or how else to ask. With [Valet+ 3.x](https://github.com/weprovide/valet-plus), the command has changed from `valet` to `valet-plus`. Does this mean that wp-cli-valet-command will no longer work with Valet+ 3.x?

**Comment by aaemnnosttv** [comment]
Hi there! This project is specific to `valet` and never claimed compatibility with other flavors or projects based on it so that much hasn't changed on this end.

As to your issue, if you don't use `valet`, you should be able to solve the issue with a symlink to effectively alias `valet-plus` as `valet` (assuming the main commands work the same way).

**Comment by ianrobertdouglas** [comment]
Thank you so much!
